# Generated by Django 4.1.7 on 2023-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetParamsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("loss", models.CharField(max_length=50)),
                ("optimizer", models.CharField(max_length=50)),
                ("lr", models.FloatField()),
                ("epochs", models.PositiveIntegerField()),
                ("batch", models.PositiveIntegerField()),
                ("layers", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
